name: my first workflow
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: "Hello from job one"
      - run: "world form job one"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: "this is is from job 2"